### ISSUE TITLE
Remove colour scheme choice for first release

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/DECIDE-app#1]
We will remove the choice of colour schemes for the first release. There are currently five in there for evaluation purposes.

**Comment by AugustT** [comment]
The reds colour scheme doesn't have enough variation in it for me to see the difference between cells 
![Screenshot_2021-05-27-08-56-36](https://user-images.githubusercontent.com/3987564/119787945-a0c68200-bec9-11eb-9d85-7da2f9e7c04a.png)
Orange to red is a little better

**Comment by burkmarr** [comment]
I agree - I prefer the yellow - orange - red scale now that I've seen them in action.

**Comment by burkmarr** [comment]
@mjopocock @cagatayTurkay @GregMci @AugustT - Unless anyone has any objections, I propose to use the yellow through red colour scheme for the first release.

**Comment by AugustT** [comment]
@burkmarr I agree

**Comment by mjopocock** [comment]
@burkmarr Fine with me too
