### ISSUE TITLE
Additional basemap layer

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/DECIDE-app#10]
@mjopocock @AugustT 

On the staging deployment I've added a grey-scale backdrop (Stamen Toner Light) which you can select from the layer control at the top-right of the map. As @GregMci and @cagatayTurkay have suggested, it helps make the DECIDE information the main feature. 

A couple of questions for you:

1. Are you happy to keep this background option in the first production release.
2. What do you think of making this the default backrop? 

(@GregMci and @cagatayTurkay - I'm sorry we can't make the staging cluster accessible to you to see this for yourself. I deployed it there rather than on production because we should avoid making too frequent changes there.) 

![image](https://user-images.githubusercontent.com/9275178/120021390-e9be2980-bfe2-11eb-8d8b-ca1541e7c262.png)

**Comment by mjopocock** [comment]
I really like the Stamen for the 'first view' of the app. It gives a clarity that really focuses my attention on the DECIDE scores.
But I quickly want to see the background to interpret the scores. 
I wonder if the switch to OSM background could be on the panel on the left, so I can easily switch between the two in the same place as the layers?
 @GregMci  @cagatayTurkay Is that a sensible way of allowing people to interact?

**Comment by AugustT** [comment]
Looks great and teases what is to come. Sounds from the OP as though this can already be toggled on and off, so looks good to me.

**Comment by burkmarr** [comment]
I'm currently using the default Leaflet control for managing the background layer - this is at the top-right of of the map. I'd rather leave control of the background layer with the built-in Leaflet control for now - 1) because it's cleaner code, 2) because I want to avoid comlicating adding controls to the panel if possible and 3) most pepole used to using slippy maps are used to looking for a control on the map to change backgrounds. I propose I leave it where it is for now, but keep the option open to change it in response to feedback from Rachel's sessions. I will change the initial display to the Stamen Toner.

**Comment by cagatayTurkay** [comment]
Thanks Rich, looks great! Using the Stamen as the default with the option for OSM toggling sounds good. 

A minor suggestion -- I believe the black lines overlaid on the map is the "rights of way" layer? We might consider adding a bit transparency or using a shade of grey for these lines -- they seem rather prominent and might be interacting too strongly with the main message in relation to the score layer. One danger over the Stamen grayscale map is that the lines might start looking like they are from the base-map layer but there should be a value to make them look sufficiently different without being too prominent.

**Comment by burkmarr** [comment]
@cagatayTurkay - @mjopocock also suggested changing the rights of way lines to a grey (as well as one or two of the other access layers). So I have done these as you will see in the next release. I think that we may well have quite a bit of tweaking to do on colours, not least because what you think might work well does not always look the way you imagined it would once implemented. I'm guessing we will also get feedback from users on the colours from the up-coming trials, so probably best not to worry too much about these now.
