### ISSUE TITLE
Add iRecord/iSpot user pref

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/DECIDE-app#17]
Add user preferences to store iSpot and iRecord usernames plus consent checkbox and notice associated witht these.

**Comment by mjopocock** [comment]
Hi @burkmarr 
I have updated a document with a full consent notice for the point of registration. I think that it is valuable to make sure this is as comprehensive as possible now so we have as little need to update them in the future. I think that we will need specific opt ins as well to cover us.

The relevant section is "Consent when registering"
The document is here:
https://teams.microsoft.com/l/file/CE954CC2-4434-4BA5-BD18-6501C16EDC2F?tenantId=7f025136-39f3-4f2c-a3c6-cbb1ce21b36a&fileType=docx&objectUrl=https%3A%2F%2Fcehacuk.sharepoint.com%2Fsites%2FUKCEHAdaptiveCS%2FShared%20Documents%2FYR1%20Tool%20development%20and%20co-design%2FGDPR%20and%20privacy.docx&baseUrl=https%3A%2F%2Fcehacuk.sharepoint.com%2Fsites%2FUKCEHAdaptiveCS&serviceName=teams&threadId=19:542c33bab12543139b144b07027552f2@thread.tacv2&groupId=243b6b46-d634-4c4f-8d9b-5bedda9e2275
