### ISSUE TITLE
Update user agreement (t&c) page

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/DECIDE-app#18]
@burkmarr 
I have added a full t&c page that I think should replace the text on the current page here: https://decide.ceh.ac.uk/info/personal_info

It is the section "User agreement page" on this document:
https://teams.microsoft.com/l/file/CE954CC2-4434-4BA5-BD18-6501C16EDC2F?tenantId=7f025136-39f3-4f2c-a3c6-cbb1ce21b36a&fileType=docx&objectUrl=https%3A%2F%2Fcehacuk.sharepoint.com%2Fsites%2FUKCEHAdaptiveCS%2FShared%20Documents%2FYR1%20Tool%20development%20and%20co-design%2FGDPR%20and%20privacy.docx&baseUrl=https%3A%2F%2Fcehacuk.sharepoint.com%2Fsites%2FUKCEHAdaptiveCS&serviceName=teams&threadId=19:542c33bab12543139b144b07027552f2@thread.tacv2&groupId=243b6b46-d634-4c4f-8d9b-5bedda9e2275

**Comment by burkmarr** [comment]
@mjopocock - I've updated the markdown: https://github.com/BiologicalRecordsCentre/DECIDE-app/blob/main/infopages/md/personal_info.md

That means it's ready to be pulled onto the SAN if you are happy with it.
