### ISSUE TITLE
Review initial settings for overall transparency and threshold

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/DECIDE-app#2]
I've changed the initial transparency setting to 0.5 and the initial threshold to 0.4. The threshold now works on percentiles. These initial levels need reviewing in view of whatever colour scheme we decide upon.

**Comment by AugustT** [comment]
I think the threshold is good.

The transparency is good but with the current reds colour scheme it makes all the reds look the same

**Comment by AugustT** [comment]
@burkmarr I approve these settings with the yellow to red scheme
