### ISSUE TITLE
Add disclaimer

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/DECIDE-app#20]
We need a disclaimer on the map page saying something like:
"The information in this tool is advisory. Information is provided in good faith, but this should not be taken as a legal basis for right of access. In all circumstances. In all circumstances, it is the user's responsibility to prioritise their own health and safety."

**Comment by burkmarr** [comment]
@mjopocock - do you want this displayed over the map? It will take up a very large amount of space in mobile view. Would a better place for it be at the foot of the map controls panel in the side-menu?

**Comment by burkmarr** [comment]
@mjopocock I've added the above text to the user_agreement text (https://github.com/BiologicalRecordsCentre/DECIDE-app/blob/main/infopages/md/user_agreement.md) - let me know what shorter version you want to add to the top of the map page opts.

**Comment by mjopocock** [comment]
How about this:
Remember - keeping safe and legal when recording is <a>your responsibility</a>.
link is to the t&c page
