### ISSUE TITLE
Change 'fader' to transparency

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/DECIDE-app#3]
Initially raised by advaith.

**Comment by AugustT** [comment]
@burkmarr Agree

**Comment by burkmarr** [comment]
Looking at this today I realised that if we call it transparency, we probably need to change the direction of the slider since currently moving the slider to the maximum gives maximum opacity, not maxiumum transparency. So I've changed the label to 'Layer opacity'. If anyone strongly feels that we should use 'transparency' rather than opacity, let me know here and I will change the label and reverse the effect of the slider. 

For CEH folk, the new label is currently on the staging deployment (https://decide.staging.ceh.ac.uk/).
