### ISSUE TITLE
Add feedback button to map screen

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/DECIDE-app#5]
Can you add a button that links to a survey page (to be set up next week) so we can get feedback. Ideally it should be prominent - maybe in the bottom right corner?

**Comment by burkmarr** [comment]
Links/buttons added, but the survey page currently not implemented, so the link currently points to the CEH website homepage.

**Comment by burkmarr** [comment]
See https://github.com/BiologicalRecordsCentre/DECIDE-app/issues/22
