### ISSUE TITLE
Add version number

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/DECIDE-app#6]
In order to make the progression clear, could you add "v0.1" to various places in the app. I suggest at least:
- "DECIDE score map" at top of map screen -> "DECIDE score map v0.1"
- Feedback button = "Feedback on v0.1"

**Comment by burkmarr** [comment]
Okay.

**Comment by burkmarr** [comment]
Links/buttons added, but the survey page currently not implemented, so the link currently points to the CEH website homepage.
