### ISSUE TITLE
Remove twitter feeds?

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/DECIDE-app#7]
The twitter feeds on the Information pages seem quite dominant. I suggest that they could be removed?

**Comment by burkmarr** [comment]
I can do that. The reason I put them in was that these information pages are based on simple Markdown pages - we can't do a multiple column display so on large screens the spacn of the text is very wide. I will take them out in a way that they can be easily reinstated if required.

**Comment by AugustT** [comment]
Agree
