### ISSUE TITLE
Update info text

### ISSUE THREAD

**Issue by mjopocock** [BiologicalRecordsCentre/DECIDE-app#8]
This is a holding issue because I am working on the improved text for the Intro pages on the app. I will have a version available on Wednesday.

My plan is to have a fairly short landing page, and add an FAQ page.

**Comment by burkmarr** [comment]
Okay no problems.

**Comment by burkmarr** [comment]
Infopage markdown and associated resources now added to this repository from where they can be pulled onto the CEH LAN where the app expects to find them.
